"""empty message

Revision ID: dc56bd666e64
Revises: bc52b28f6629
Create Date: 2019-11-28 09:55:02.443173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc56bd666e64'
down_revision = 'bc52b28f6629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('genre', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_book_genre'), 'book', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_genre'), table_name='book')
    op.drop_column('book', 'genre')
    # ### end Alembic commands ###
